image: docker:20.10.2

services:
  - docker:20.10.2-dind

include:
  - /ci-pipelines/merge-requests.yaml
  - /ci-pipelines/deployments.yaml

stages:
  - pre_test
  - test
  - pre_publish
  - publish
  - deploy

variables:
  NODE_VERSION: 14.15.4

before_script:
  - apk update
  - apk add --no-cache curl bash libgcc libstdc++
  - export PATH=$PATH:$CI_PROJECT_DIR/.node/bin
