image: docker:19.03.12

services:
  - docker:19.03.12-dind

test_all:
  stage: test
  only:
    - merge_requests
  script:
    - apk update
    - apk add --no-cache docker-compose
    - apk add --no-cache wget
    - wget https://nodejs.org/dist/v14.15.4/node-v14.15.4-linux-x64.tar.xz && tar -xf node-v14.15.4-linux-x64.tar.xz
    - ln -s node-v14.15.4-linux-x64/bin/node /usr/local/bin/node
    - ln -s node-v14.15.4-linux-x64/bin/npm /usr/local/bin/npm
    - node -v && npm -v
    - npm i -g pnpm
    - pnpm i --frozen-lockfile
    - pnpm test
    - pnpm test:e2e
