image: docker:20.10.2

services:
  - docker:20.10.2-dind

stages:
  - pre_test
  - test
  - publish
  - deploy

variables:
  NODE_VERSION: 14.15.4

before_script:
  - apk update
  - apk add --no-cache curl bash libgcc libstdc++
  - curl -OJs https://unofficial-builds.nodejs.org/download/release/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64-musl.tar.xz
  - tar -xf node-v$NODE_VERSION-linux-x64-musl.tar.xz -C /opt
  - ln -s /opt/node-v$NODE_VERSION-linux-x64-musl/bin/node /usr/local/bin/node
  - ln -s /opt/node-v$NODE_VERSION-linux-x64-musl/bin/npm /usr/local/bin/npm
  - ln -s /opt/node-v$NODE_VERSION-linux-x64-musl/bin/npx /usr/local/bin/npx
  - export PATH=$PATH:$(npm config get prefix)/bin

pre_test:
  stage: pre_test
  only:
    - merge_requests
  cache:
    key: lol
    paths:
      - /opt/node-v$NODE_VERSION-linux-x64-musl/bin
      - /opt/node-v$NODE_VERSION-linux-x64-musl/lib
      - node_modules/
      - src/webapi/node_modules/
      - src/lib/node_modules/
  script:
    - apk add --no-cache docker-compose
    - npm i -g pnpm
    - pnpm i --frozen-lockfile

.test_package:
  stage: test
  only:
    - merge_requests
  cache:
    key: lol
  script:
    - cd $APP_PATH
    - pnpm test:all

test_lib:
  extends: .test_package
  variables:
    APP_PATH: src/lib

test_webapi:
  extends: .test_package
  variables:
    APP_PATH: src/webapi

# https://gitlab.com/gitlab-org/gitlab/-/issues/16376#note_214904350
.setup_heroku: &setup_heroku |-
  curl https://cli-assets.heroku.com/install.sh | sh
  heroku container:login

.publish_app:
  stage: publish
  only:
    - main
  script:
    - *setup_heroku
    - cd $APP_PATH
    - heroku container:push --context-path ../../ web

publish_webapi:
  extends: .publish_app
  variables:
    HEROKU_APP: typescript-monorepo
    APP_PATH: src/webapi

deploy:
  stage: deploy
  only:
    - main
  script:
    - *setup_heroku
    - heroku container:release web --app=typescript-monorepo
