name: Delete images for closed PRs

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  delete-unused-images:
    name: Delete unused image tags
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == false
    strategy:
      matrix:
        name: [web-api, internal-api]
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Delete PR image if exists
        run: |
          PACKAGE_NAME=${{ env.GITHUB_REPOSITORY_NAME_PART }}-${{ env.GITHUB_BASE_REF_SLUG }}-${{ matrix.name }}
          IMAGE_ID=$(curl -s \
            -H 'Authorization: Bearer ${{ secrets.DOCKER_TOKEN }}' \
            -H 'Accept: application/vnd.github.v3+json' \
            "https://api.github.com/user/packages/container/$PACKAGE_NAME/versions" \
            | jq -rM '.[] | select(.metadata.container.tags | index("${{ github.event.pull_request.number }}")).id // null' \
            || echo null
          )
          if [ "$IMAGE_ID" != 'null' ]; then
            curl -i \
              -X DELETE \
              -H 'Authorization: Bearer ${{ secrets.DOCKER_TOKEN }}' \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/user/packages/container/$PACKAGE_NAME/versions/$IMAGE_ID"
            echo "Image id $IMAGE_ID with tag ${{ github.event.pull_request.number }} deleted"
          else
            echo "Image id not found"
          fi
