name: Tests

on:
  pull_request:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

anchors:
  pnpm-setup: &pnpm-setup
    - uses: actions/setup-node@v2
      with:
        node-version: '14.15.4'
    - name: Set global npm folder
      run: |
        mkdir ~/.npm-global
        npm config set prefix '~/.npm-global'
        echo "$HOME/.npm-global/bin" >> $GITHUB_PATH
    - name: Cache npm global folder
      id: cache-npm-global
      uses: actions/cache@v2
      with:
        path: ~/.npm-global
        key: ${{ runner.os }}-tests-npm-global
    - name: Install global node packages
      if: steps.cache-npm-global.outputs.cache-hit != 'true'
      run: |
        npm i -g pnpm
  node-modules-cache: &node-modules-cache
    uses: actions/cache@v2
    with:
      path: '**/node_modules'
      key: ${{ runner.os }}-tests-node-modules-${{ github.sha }}

jobs:
  pre-test:
    name: Pre-test
    runs-on: ubuntu-20.04
    steps:
      - *pnpm-setup
      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-tests-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-tests-pnpm-store-
      - <<: *node-modules-cache
      - uses: actions/checkout@v2
      - run: pnpm i --frozen-lockfile
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-20.04
    needs: [pre-test]
    strategy:
      matrix:
        path: [src/lib, src/web-api]
    defaults:
      run:
        working-directory: ${{ matrix.path }}
    steps:
      - *pnpm-setup
      - <<: *node-modules-cache
      - run: pnpm lint
      - run: pnpm test:unit
  apps-docker-build:
    name: 'Apps: docker build'
    runs-on: ubuntu-20.04
    needs: [unit-tests]
    strategy:
      matrix:
        include:
          - app-name: web-api
            path: src/web-api
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login ghcr.io -u rhyek --password-stdin
      - name: Set image name
        run: echo "IMAGE=ghcr.io/$GITHUB_REPOSITORY-${{ matrix.app-name }}" >> $GITHUB_ENV
      - name: Build docker image
        run: |
          docker build \
            -t ${{ env.IMAGE }}:${{ github.sha }} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from=${{ env.IMAGE }}:latest \
            --cache-from=${{ env.IMAGE }}:${{ github.sha }} \
            -f ${{ matrix.path }}/Dockerfile \
            .
      - name: Docker push
        run: docker push ${{ env.IMAGE }}:${{ github.sha }}
  apps-integration-tests:
    name: 'Apps: integration tests'
    runs-on: ubuntu-20.04
    needs: [apps-docker-build]
    strategy:
      matrix:
        include:
          - app-name: web-api
            path: src/web-api
    defaults:
      run:
        working-directory: ${{ matrix.path }}
    steps:
      - *pnpm-setup
      - <<: *node-modules-cache
      - run: pnpm test:e2e
