name: Publish and Deploy

on:
  push:
    branches:
      - main
env:
  !include(../includes/envs)
  !include(../includes/push-envs)

anchors:
  !include(../includes/common-anchors)
  !include(../includes/apps)
  report: &report
    name: Slack Notification
    uses: rtCamp/action-slack-notify@v2
    if: cancelled() || failure()
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_USERNAME: github-actions
      SLACK_COLOR: ${{ job.status == 'success' && 'good' || job.status == 'cancelled' && '#808080' || 'danger' }}
  set-image-names: &set-image-names
    name: Set image names
    id: image-names
    run: |
      echo "::set-output name=github::${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}-${{ env.GITHUB_REF_SLUG }}-${{ matrix.name }}"
      echo "::set-output name=heroku::registry.heroku.com/${{ env[matrix.heroku_app_key] }}/web"
  heroku-docker-login: &heroku-docker-login
    name: Heroku Docker login
    run: echo ${{ secrets.HEROKU_API_KEY }} | docker login registry.heroku.com --username=_ --password-stdin

jobs:
  pr-number:
    name: Get PR number
    runs-on: ubuntu-20.04
    outputs:
      result: ${{ steps.pr-number.outputs.result }}
    steps:
      - name: Get PR number
        id: pr-number
        run: |
          NUMBER=$(curl \
            -s \
            -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'accept: application/vnd.github.groot-preview+json' \
            'https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls' \
            | jq -rM '.[0].number' 2> /dev/null \
            || echo null
          )
          echo "::set-output name=result::$NUMBER"

  pnpm-store-cache: # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
    name: Create pnpm store cache for future PRs
    runs-on: ubuntu-20.04
    needs: pr-number
    if: needs.pr-number.outputs.result != 'null'
    steps:
      - uses: actions/checkout@v2
      - <<: *pnpm-store-cache
      - *setup-pnpm
      - run: pnpm i --frozen-lockfile

  publish-for-pr:
    name: Publish images for merged PR
    runs-on: ubuntu-20.04
    needs: pr-number
    if: needs.pr-number.outputs.result != 'null'
    strategy:
      matrix:
        include:
          *push-publish-for-pr-matrix
    steps:
      - *setup-node
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - <<: *docker-login
      - <<: *set-image-names
      - name: Check if image for PR exists
        id: image-exists
        run: |
          docker pull ${{ env.DOCKER_REPOSITORY }}/${{ steps.image-names.outputs.github }}:${{ needs.pr-number.outputs.result }} && EXIT_CODE=0 || EXIT_CODE=$?
          RESULT=$([ $EXIT_CODE = 0 ] && echo 'true' || echo 'false')
          echo "::set-output name=result::$RESULT"
      - <<: *heroku-docker-login
        if: steps.image-exists.outputs.result == 'true' && matrix.heroku_app_key != ''
      - name: Tag and push to heroku
        if: steps.image-exists.outputs.result == 'true' && matrix.heroku_app_key != ''
        run: |
          docker tag ${{ env.DOCKER_REPOSITORY }}/${{ steps.image-names.outputs.github }}:${{ needs.pr-number.outputs.result }} ${{ steps.image-names.outputs.heroku }}
          docker push ${{ steps.image-names.outputs.heroku }}
      - name: Tag 'latest' and push to ghcr
        id: push-to-ghcr
        if: steps.image-exists.outputs.result == 'true'
        run: |
          tag_latest_if_pr_image_exists () {
            local IMAGE_NAME=$1

            docker buildx imagetools inspect \
              "${{ env.DOCKER_REPOSITORY }}/$IMAGE_NAME:${{ needs.pr-number.outputs.result }}" &> /dev/null && EXIT_CODE=0 || EXIT_CODE=$?

            if [ $EXIT_CODE = 0 ]; then
              docker buildx imagetools create \
                -t "${{ env.DOCKER_REPOSITORY }}/$IMAGE_NAME:latest" \
                "${{ env.DOCKER_REPOSITORY }}/$IMAGE_NAME:${{ needs.pr-number.outputs.result }}"
            fi
          }

          tag_latest_if_pr_image_exists ${{ steps.image-names.outputs.github }}
          tag_latest_if_pr_image_exists ${{ steps.image-names.outputs.github }}-cache
      - <<: *report
  publish-for-push:
    name: Publish images for direct push
    runs-on: ubuntu-20.04
    needs: pr-number
    if: needs.pr-number.outputs.result == 'null'
    strategy:
      matrix:
        include:
          *push-publish-for-push-matrix
    steps:
      - uses: actions/checkout@v2
      - <<: *pnpm-store-cache
      - *setup-pnpm
      - run: pnpm i --frozen-lockfile
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - <<: *docker-login
      - <<: *heroku-docker-login
      - <<: *set-image-names
      - uses: docker/setup-buildx-action@v1
      - name: Build and Push docker image
        run: |
          .scripts/make-dedicated-lockfile.ts ${{ matrix.name }} --replace
          docker -v
          docker buildx version
          docker buildx build \
            --cache-from=${{ env.DOCKER_REPOSITORY }}/${{ steps.image-names.outputs.github }}:latest \
            --cache-to=type=inline \
            -t ${{ env.DOCKER_REPOSITORY }}/${{ steps.image-names.outputs.github }}:latest \
            -t ${{ steps.image-names.outputs.heroku }} \
            -f $(.scripts/dir-for-app.ts ${{ matrix.name }})/Dockerfile \
            --push \
            .
      - <<: *report
  deploy:
    name: Deploy apps
    runs-on: ubuntu-20.04
    needs: [publish-for-pr, publish-for-push]
    if: always() && (needs.publish-for-pr.result == 'success' || needs.publish-for-push.result == 'success')
    steps:
      - *setup-node
      - run: curl -s https://cli-assets.heroku.com/install.sh | sh
      - run: heroku container:login
      - *push-deploy-apps
      - <<: *report
        if: always()
