# https://gitlab.com/gitlab-org/gitlab/-/issues/16376#note_214904350
.setup_heroku: &setup_heroku |-
  curl https://cli-assets.heroku.com/install.sh | sh
  heroku container:login

.publish_app:
  stage: publish
  only:
    - main
  script:
    - *setup_heroku
    - cd $APP_PATH
    - heroku container:push --context-path ../../ web

publish_webapi:
  extends: .publish_app
  variables:
    HEROKU_APP: typescript-monorepo
    APP_PATH: src/webapi

deploy:
  stage: deploy
  only:
    - main
  script:
    - *setup_heroku
    - heroku container:release web --app=typescript-monorepo
