name: Tests
'on':
  pull_request:
    branches:
      - main
env:
  DOCKER_BUILDKIT: 1
jobs:
  print-usable-sha:
    name: Rofl!
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{ github.event.pull_request.head.sha }}
