name: Tests
'on':
  pull_request:
    branches:
      - main
env:
  DOCKER_BUILDKIT: 1
jobs:
  debug-github-context:
    name: lmao
    runs-on: ubuntu-20.04
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
