name: Tests
'on':
  pull_request:
    branches:
      - main
jobs:
  pre-test:
    name: Pre-test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.4
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile
  test-libs:
    name: Test libs
    runs-on: ubuntu-20.04
    needs:
      - pre-test
    strategy:
      matrix:
        path:
          - src/lib
    defaults:
      run:
        working-directory: ${{ matrix.path }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.4
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - run: npm i -g pnpm
      - run: pnpm lint
      - run: pnpm test:unit
  test-apps:
    name: Test apps
    runs-on: ubuntu-20.04
    needs:
      - pre-test
    strategy:
      matrix:
        path:
          - src/webapi
    defaults:
      run:
        working-directory: ${{ matrix.path }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.4
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - run: npm i -g pnpm
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test:unit
      - run: pnpm test:e2e
