name: Tests
'on':
  pull_request:
    branches:
      - main
env:
  DOCKER_BUILDKIT: 1
jobs:
  lint-unit:
    name: Lint and Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.17.2
      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: >-
            ${{ runner.os }}-tests-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml')
            }}
          restore-keys: |
            ${{ runner.os }}-tests-pnpm-store-
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-tests-node-modules-${{ github.sha }}
      - run: pnpm i --frozen-lockfile
      - name: Fetch target branch
        run: >-
          git fetch --no-tags --prune --depth=1 origin +refs/heads/${{
          github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      - run: pnpx ts-node -T .scripts/ci/run-lint
      - run: pnpx ts-node -T .scripts/ci/run-tests unit
