name: Build and Deploy
'on':
  push:
    branches:
      - main
jobs:
  lol:
    name: lmao
    runs-on: ubuntu-20.04
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
