#!/bin/bash

set -e

export COMPOSE_PROJECT_NAME=web-api-e2e
export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_BUILDKIT=1
if [ "$CI" = "true" ]; then
  docker-compose -f docker-compose.yaml -f docker-compose.ci.yaml up --build --detach
else
  docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up --build --detach
fi

ttsc -b ../tsconfig.test.json

INTERNAL_API_PORT=4001 jest --runInBand
